### PR TITLE
Content updates

### PR DESCRIPTION
**Pull request by nathancashmoredwp**

### CODE REVIEW

**Comment by lukasz-kaniowski** [comment]
👍 you went commit mad here ;)

**Comment by nathancashmoredwp** [comment]
@jeansims can you check this out and let me know its good.

**Comment by jeansims** [comment]
I'll check this asap!

**Comment by jeansims** [comment]
Activity re-sort
https://activity-prompt-prototype.herokuapp.com/claimant/to-do/activity-prompt/prototype/action?resort=true
There is now a text link that says 'Move' next to the details button for all tasks when people want to re-categorise the task.

Find activities that can help you get work
https://activity-prompt-prototype.herokuapp.com/claimant/to-do/activity-prompt/prototype/index 
On this page 'ten' should be '10'. Full stop needed after the word 'list' in point 1.

Choose some activities
https://activity-prompt-prototype.herokuapp.com/claimant/to-do/activity-prompt/prototype/unsorted-list
Page heading should be 'Choose your activities' rather than 'Choose some activities'. 
This task should be at the bottom of the list - Do you need to do anything about the basics - maths or English?

Register with recruitment agencies
https://activity-prompt-prototype.herokuapp.com/claimant/to-do/activity-prompt/prototype/details?prompt=Register%20with%20recruitment%20agencies
In second sentence need to hyphenate full time in this instance - it should be 'full-time jobs'.
Also there is a sentence missing under the list of websites.

**Comment by jeansims** [comment]
**Find out how social media websites like LinkedIn can help with your search**
https://choose-your-activities-pr-60.herokuapp.com/ec181d17-5597-4239-9419-197c867e2053/activities/ACT-14
In the sentence 'Having a informative' change 'a' to 'an' sentence should be ' Having an informative'

**Plan your work search for the week**
https://choose-your-activities-pr-60.herokuapp.com/ec181d17-5597-4239-9419-197c867e2053/activities/ACT-16
'Ask your Work Coach' -work coach needs to be lowercase, ie 'work coach'.

**Make a list of a few jobs you’d like in a year from now and the skills you need for them**
https://choose-your-activities-pr-60.herokuapp.com/ec181d17-5597-4239-9419-197c867e2053/activities/ACT-17/categorise
When I want to view this page it keeps looping me back to the select 'category option'. I can't seem to view the 'details' page using the navigation  

**You've sorted all of the activities**
https://activity-prompt-prototype.herokuapp.com/claimant/to-do/activity-prompt/prototype/unsorted-list?prompt=Register+with+recruitment+agencies&category=I%27m+ready+to+try+this
When all the activities are sorted there is new text and a green 'Continue' button.

**Rearrange your list**
https://choose-your-activities-pr-60.herokuapp.com/ec181d17-5597-4239-9419-197c867e2053/activities/re-sort
New text and functionality for this - speak to @jessstubenbord for details.

**Comment by nathancashmore** [comment]
Rearrange I'll pick up in a different PR .. the rest I'll look into.

**Comment by jeansims** [comment]
https://choose-your-activities-pr-60.herokuapp.com/9f9e0be9-e4ad-42bb-8733-039d23cdb56d/introduction
This point needs a full stop at the end of it '1. Look through the list.'

**Comment by nathancashmoredwp** [comment]
@jeansims how does that look

**Comment by jeansims** [comment]
Thanks @nathancashmoredwp https://choose-your-activities-pr-60.herokuapp.com/9f9e0be9-e4ad-42bb-8733-039d23cdb56d/introduction looks good no further changes from me.

**Comment by jeansims** [comment]
@nathancashmoredwp sorry the change to Register with recruitment agencies needs an amend I'm afraid.

https://activity-prompt-prototype.herokuapp.com/claimant/to-do/activity-prompt/prototype/details?prompt=Register%20with%20recruitment%20agencies

Just need to hyphenate the word full-time in this instance so it's - full-time jobs. 

Please remove speech marks/inverted commas from around the words full-time jobs.

**Comment by nathancashmoredwp** [comment]
This ship has sailed @jeansims, i'll pick this up in another PR.

**Pull request merged**
